name: finscout-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - crewai==0.30.11
    - crewai-tools==0.1.6
    - streamlit==1.35.0
    - python-dotenv==1.0.1
    - beautifulsoup4==4.12.3
    - requests==2.31.0
    - lxml==5.2.1
    - chromadb==0.5.0
    - langchain-community==0.0.38
    - ollama==0.2.0
    - sentence-transformers==2.7.0
    - InstructorEmbedding==1.0.1
    - PyMuPDF==1.24.1
    - langchain_experimental==0.0.58
    - tiktoken==0.7.0
    - pandas==2.2.2
    - playwright==1.44.0